//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpbuEducation.TimeTable.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpbuEducation.TimeTable.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all classes.
        /// </summary>
        public static string allClasses {
            get {
                return ResourceManager.GetString("allClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All years.
        /// </summary>
        public static string AllYears {
            get {
                return ResourceManager.GetString("AllYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autumn semester.
        /// </summary>
        public static string autumnSemester {
            get {
                return ResourceManager.GetString("autumnSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string BreadcrumbRoot {
            get {
                return ResourceManager.GetString("BreadcrumbRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course.
        /// </summary>
        public static string course {
            get {
                return ResourceManager.GetString("course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of study.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields of study.
        /// </summary>
        public static string Divisions {
            get {
                return ResourceManager.GetString("Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer.
        /// </summary>
        public static string Educator {
            get {
                return ResourceManager.GetString("Educator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturers not found by search query.
        /// </summary>
        public static string EducatorNotFound {
            get {
                return ResourceManager.GetString("EducatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturers.
        /// </summary>
        public static string Educators {
            get {
                return ResourceManager.GetString("Educators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elective.
        /// </summary>
        public static string elective {
            get {
                return ResourceManager.GetString("elective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events were found.
        /// </summary>
        public static string EventsNotFound {
            get {
                return ResourceManager.GetString("EventsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracurricular.
        /// </summary>
        public static string Extracurricular {
            get {
                return ResourceManager.GetString("Extracurricular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facultative.
        /// </summary>
        public static string facultative {
            get {
                return ResourceManager.GetString("facultative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to final attestation.
        /// </summary>
        public static string finalAttestation {
            get {
                return ResourceManager.GetString("finalAttestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event with agenda.
        /// </summary>
        public static string HasAgenda {
            get {
                return ResourceManager.GetString("HasAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interim attestation.
        /// </summary>
        public static string interimAttestation {
            get {
                return ResourceManager.GetString("interimAttestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediary attestation for the previous.
        /// </summary>
        public static string IntermediaryAttestationForPrevious {
            get {
                return ResourceManager.GetString("IntermediaryAttestationForPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long events.
        /// </summary>
        public static string LongEvents {
            get {
                return ResourceManager.GetString("LongEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next week ›.
        /// </summary>
        public static string nextWeek {
            get {
                return ResourceManager.GetString("nextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical training.
        /// </summary>
        public static string PhysTraining {
            get {
                return ResourceManager.GetString("PhysTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‹ previous week.
        /// </summary>
        public static string previousWeek {
            get {
                return ResourceManager.GetString("previousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a lecturer.
        /// </summary>
        public static string SearchEducator {
            get {
                return ResourceManager.GetString("SearchEducator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by lastname....
        /// </summary>
        public static string SearchEducatorByLastname {
            get {
                return ResourceManager.GetString("SearchEducatorByLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        public static string SearchEventsPast {
            get {
                return ResourceManager.GetString("SearchEventsPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string SearchEventsUpcoming {
            get {
                return ResourceManager.GetString("SearchEventsUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for events....
        /// </summary>
        public static string SearchForEvents {
            get {
                return ResourceManager.GetString("SearchForEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPbU timetables.
        /// </summary>
        public static string SpbuTimetable {
            get {
                return ResourceManager.GetString("SpbuTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spring semester.
        /// </summary>
        public static string springSemester {
            get {
                return ResourceManager.GetString("springSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student group.
        /// </summary>
        public static string StudentGroup {
            get {
                return ResourceManager.GetString("StudentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational programme.
        /// </summary>
        public static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational programmes.
        /// </summary>
        public static string StudyPrograms {
            get {
                return ResourceManager.GetString("StudyPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational programme timetables.
        /// </summary>
        public static string StudyProgramTimetables {
            get {
                return ResourceManager.GetString("StudyProgramTimetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        public static string Timetable {
            get {
                return ResourceManager.GetString("Timetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer&apos;s timetable:.
        /// </summary>
        public static string TimetableForEducator {
            get {
                return ResourceManager.GetString("TimetableForEducator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetables.
        /// </summary>
        public static string Timetables {
            get {
                return ResourceManager.GetString("Timetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetables for.
        /// </summary>
        public static string TimeTablesFor {
            get {
                return ResourceManager.GetString("TimeTablesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturers timetables.
        /// </summary>
        public static string TimetablesForEducators {
            get {
                return ResourceManager.GetString("TimetablesForEducators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetables for this academic group are not available..
        /// </summary>
        public static string TimeTablesForGroupUnavailable {
            get {
                return ResourceManager.GetString("TimeTablesForGroupUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetables unavailable.
        /// </summary>
        public static string TimetablesUnavailable {
            get {
                return ResourceManager.GetString("TimetablesUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autumn term.
        /// </summary>
        public static string toAutumnSemester {
            get {
                return ResourceManager.GetString("toAutumnSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to current month.
        /// </summary>
        public static string toCurrentMonth {
            get {
                return ResourceManager.GetString("toCurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a week.
        /// </summary>
        public static string ToCurrentWeek {
            get {
                return ResourceManager.GetString("ToCurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to semester.
        /// </summary>
        public static string toSemester {
            get {
                return ResourceManager.GetString("toSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spring term.
        /// </summary>
        public static string ToSpringSemester {
            get {
                return ResourceManager.GetString("ToSpringSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current week.
        /// </summary>
        public static string toStart {
            get {
                return ResourceManager.GetString("toStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to week.
        /// </summary>
        public static string toWeek {
            get {
                return ResourceManager.GetString("toWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a term.
        /// </summary>
        public static string ToWholeSemester {
            get {
                return ResourceManager.GetString("ToWholeSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string XtracurEventAgenda {
            get {
                return ResourceManager.GetString("XtracurEventAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event was cancelled.
        /// </summary>
        public static string XtracurEventCancelled {
            get {
                return ResourceManager.GetString("XtracurEventCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the event is not available.
        /// </summary>
        public static string XtracurEventNoData {
            get {
                return ResourceManager.GetString("XtracurEventNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year of admission.
        /// </summary>
        public static string yearOfAdmission {
            get {
                return ResourceManager.GetString("yearOfAdmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of admission.
        /// </summary>
        public static string YearsOfAdmission {
            get {
                return ResourceManager.GetString("YearsOfAdmission", resourceCulture);
            }
        }
    }
}
